apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoserver
  template:
    metadata:
      labels:
        app: demoserver
    spec:
      containers:
        - name: demoserver
          image: satsarode/demoserver:1.0
          ports:
            - containerPort: 9300
          env:
            - name: CSVSERVER_BORDER
              value: Orange
---
apiVersion: v1
kind: Service
metadata:
  name: demoserver-service
spec:
  selector:
    app: demoserver
  ports:
    - protocol: TCP
      port: 9300
      targetPort: 9300
  type: NodePort
